INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (1,'eBusiness Suite');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (2,'NYSE');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (3,'OMB Circular A-133');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (4,'SFP');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (5,'Crossbeam XOS');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (6,'DMC');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (7,'Ffmpeg');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (8,'CCVP');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (9,'Military Logistics');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (10,'DVD Studio Pro');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (11,'Lightroom');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (12,'IFS ERP');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (13,'MPEG Streamclip');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (14,'SMT Kingdom');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (15,'Econometrics');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (16,'CT Summation');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (17,'cXML');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (18,'Environmental Awareness');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (19,'Wine');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (20,'IGRT');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (21,'TCP');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (22,'Working Abroad');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (23,'Foreclosures');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (24,'AXI');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (25,'Target Identification');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (26,'EMR');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (27,'Basel II');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (28,'ePub');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (29,'Yardi Property Management');
INSERT INTO greeliving.Course(CourseID,CourseName) VALUES (30,'FDTD');