INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (1,'Website Updating');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (2,'DLL');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (3,'Major Gift Development');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (4,'RLC');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (5,'Navigation');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (6,'Scheduling');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (7,'Optical Tweezers');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (8,'GPP');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (9,'RUP');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (10,'SDK');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (11,'NG-SDH');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (12,'Data Modeling');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (13,'Government');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (14,'Beauty Industry');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (15,'PDS Frameworks');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (16,'JNI');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (17,'HDPE');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (18,'Urology');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (19,'Litigation');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (20,'ESRI');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (21,'Eyelash Extensions');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (22,'XOG');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (23,'SFE');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (24,'Fine Dining');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (25,'Media TV');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (26,'Personal Injury');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (27,'IEP');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (28,'iWay');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (29,'Public Affairs');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (30,'Warranty');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (31,'Branding &amp; Identity');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (32,'Oracle HR');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (33,'TF-CBT');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (34,'cDNA');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (35,'Windows Server');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (36,'Jive SBS');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (37,'FBA');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (38,'Yeast');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (39,'NCIDQ');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (40,'High Availability');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (41,'vShield');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (42,'RTM');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (43,'uCOS');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (44,'Self-esteem');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (45,'IGRP');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (46,'EEG');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (47,'Private Equity');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (48,'DVD Replication');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (49,'PXE');
INSERT INTO greeliving.Specialization(SpecializationID,SpecializationName) VALUES (50,'CTM');